# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=20)),
                ('costRateTop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costRateBottom', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
