# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('trustScore', models.DecimalField(decimal_places=1, max_digits=3)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
