# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('ncapScore', models.CharField(choices=[('1', '1 star'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars')], max_length=8)),
                ('airbags', models.IntegerField()),
                ('noDoors', models.IntegerField()),
                ('trunkCapacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kmPerChargeTank', models.DecimalField(decimal_places=2, max_digits=7)),
                ('height', models.DecimalField(decimal_places=3, max_digits=8)),
                ('large', models.DecimalField(decimal_places=3, max_digits=8)),
                ('wide', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
