# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcas', '0001_initial'),
        ('Autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Marcas.Marca'),
        ),
    ]
